// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRpyF98Hl2SD_RgaC8DGwbn0IWZQdtiAQ',
    appId: '1:890017789779:web:0995c3fab4613c394cd3a6',
    messagingSenderId: '890017789779',
    projectId: 'home-app-aab5f',
    authDomain: 'home-app-aab5f.firebaseapp.com',
    storageBucket: 'home-app-aab5f.appspot.com',
    measurementId: 'G-Q2TE7WQ42L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKnzOguTJlDOm2Nx0-KdUobLa3Yv2pIco',
    appId: '1:890017789779:android:a94c6e2b1c1155104cd3a6',
    messagingSenderId: '890017789779',
    projectId: 'home-app-aab5f',
    storageBucket: 'home-app-aab5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqeLQ5gTfev0ab4Gz5dbgrbZQwkGYIumQ',
    appId: '1:890017789779:ios:bf8f228fd59930144cd3a6',
    messagingSenderId: '890017789779',
    projectId: 'home-app-aab5f',
    storageBucket: 'home-app-aab5f.appspot.com',
    iosBundleId: 'com.example.houseAppOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqeLQ5gTfev0ab4Gz5dbgrbZQwkGYIumQ',
    appId: '1:890017789779:ios:d43c6e41574a0cb24cd3a6',
    messagingSenderId: '890017789779',
    projectId: 'home-app-aab5f',
    storageBucket: 'home-app-aab5f.appspot.com',
    iosBundleId: 'com.example.houseAppOne.RunnerTests',
  );
}
