// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaj5E3Ok44berAbgknLasQEFOGDLjSEHg',
    appId: '1:720301637446:web:9a18d870062e3c624c2f47',
    messagingSenderId: '720301637446',
    projectId: 'home-mti',
    authDomain: 'home-mti.firebaseapp.com',
    storageBucket: 'home-mti.appspot.com',
    measurementId: 'G-SYQSV92NG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFmW6MAIyS0sRFb9EBB-0cimr7FLqtj8',
    appId: '1:720301637446:android:901691728f4b2b8e4c2f47',
    messagingSenderId: '720301637446',
    projectId: 'home-mti',
    storageBucket: 'home-mti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_1KdeVHzZ06uWc4UrY4YQaUFmMeIFkJg',
    appId: '1:720301637446:ios:e01463de0015df3a4c2f47',
    messagingSenderId: '720301637446',
    projectId: 'home-mti',
    storageBucket: 'home-mti.appspot.com',
    iosBundleId: 'com.example.houseAppOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_1KdeVHzZ06uWc4UrY4YQaUFmMeIFkJg',
    appId: '1:720301637446:ios:a4d921654e5bf5624c2f47',
    messagingSenderId: '720301637446',
    projectId: 'home-mti',
    storageBucket: 'home-mti.appspot.com',
    iosBundleId: 'com.example.houseAppOne.RunnerTests',
  );
}
